### PR TITLE
Added jktrain.txt file

### PR DESCRIPTION
**Pull request by jmkuruvilla**

### CODE REVIEW

**Comment by roninlabs-teacher** [comment]
Looks good to me

**Comment by timothylank** [comment]
sounds good

**Comment by roninlabs-teacher** [comment]
:+1: let's :ship: it

**Comment by PeterBell** [comment]
:+1: from me too - lets do this!

**Comment by PeterBell** [comment]
harry-potter-congrats

**Comment by asimon1** [comment]
:+1: from me too.  Ship it!

**Pull request merged**
